### PR TITLE
NXP-23437: use the command line converter in any2doc and any2docx.

### PR DESCRIPTION
**Pull request by richardsd**

### CODE REVIEW

**Comment by efge** [comment]
👍

**Comment by efge** [comment]
Did this go through a T&P? I'm not seeing the link to it automatically added by Jenkins.

**Comment by richardsd** [comment]
Build here https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-rdias-master/37/, but PR was not created.

**Comment by efge** [comment]
It's ok, GitHub won't allow creation of a PR for a given branch if there's already one open.

**Comment by efge** [comment]
👍

**Comment by atchertchian** [comment]
:+1: although would have been good to have a unit test

**Comment by richardsd** [comment]
I'll add a unit test to both the converters then. Thanks.

**Comment by atchertchian** [comment]
:+1:

**Pull request merged**
